import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const workspaceRoot = path.resolve(new URL('.', import.meta.url).pathname, '..');
const outFile = path.resolve(workspaceRoot, 'src', 'bundled', 'reactTypeLibs.ts');

const require = createRequire(import.meta.url);

const resolvePkgDir = (pkgName) => {
  const pkgJson = require.resolve(`${pkgName}/package.json`);
  return path.dirname(pkgJson);
};

const readText = (filePath) => fs.readFileSync(filePath, 'utf8');

const libs = [];

const addFromPackage = (pkgName, relPath) => {
  const pkgDir = resolvePkgDir(pkgName);
  const abs = path.resolve(pkgDir, relPath);
  if (!fs.existsSync(abs)) return;
  libs.push({
    filePath: `${pkgName}/${relPath}`.replace(/\\/g, '/'),
    content: readText(abs)
  });
};

// Dependencies used by @types/react
addFromPackage('@types/prop-types', 'index.d.ts');
addFromPackage('@types/scheduler', 'index.d.ts');
addFromPackage('@types/scheduler', 'tracing.d.ts');
addFromPackage('csstype', 'index.d.ts');

// React + ReactDOM types
addFromPackage('@types/react', 'global.d.ts');
addFromPackage('@types/react', 'index.d.ts');
addFromPackage('@types/react', 'jsx-runtime.d.ts');
addFromPackage('@types/react', 'jsx-dev-runtime.d.ts');
addFromPackage('@types/react', 'compiler-runtime.d.ts');
addFromPackage('@types/react', 'experimental.d.ts');
addFromPackage('@types/react', 'canary.d.ts');

addFromPackage('@types/react-dom', 'index.d.ts');
addFromPackage('@types/react-dom', 'client.d.ts');
addFromPackage('@types/react-dom', 'server.d.ts');
addFromPackage('@types/react-dom', 'server.browser.d.ts');
addFromPackage('@types/react-dom', 'experimental.d.ts');
addFromPackage('@types/react-dom', 'canary.d.ts');

const header =
  `/* This file is auto-generated by scripts/generate-typings.mjs */\n` +
  `export const REACT_TYPE_LIBS: { filePath: string; content: string }[] = ${JSON.stringify(libs)};\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, header, 'utf8');
